import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ThemeContextProvider,
  Locale,
  RegionCode,
  getMovistarSkin,
} from "@telefonica/mistica";

import "@telefonica/mistica/css/mistica.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const misticaTheme = {
    skin: getMovistarSkin(),
    i18n: {
      locale: "es-ES" as Locale,
      phoneNumberFormattingRegionCode: "ES" as RegionCode,
    },
  };

  return (
    <html lang="es">
      <body
        className={`bg-white text-black ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeContextProvider theme={misticaTheme}>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
